# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 816)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background:rgb(232, 232, 232);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:rgb(232, 232, 232);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_loadpre = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_loadpre.sizePolicy().hasHeightForWidth())
        self.button_loadpre.setSizePolicy(sizePolicy)
        self.button_loadpre.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/file_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_loadpre.setIcon(icon)
        self.button_loadpre.setObjectName("button_loadpre")
        self.horizontalLayout_6.addWidget(self.button_loadpre)
        self.button_clearpre = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clearpre.sizePolicy().hasHeightForWidth())
        self.button_clearpre.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_clearpre.setIcon(icon1)
        self.button_clearpre.setObjectName("button_clearpre")
        self.horizontalLayout_6.addWidget(self.button_clearpre)
        self.line_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.button_signal = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_signal.sizePolicy().hasHeightForWidth())
        self.button_signal.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/variable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_signal.setIcon(icon2)
        self.button_signal.setObjectName("button_signal")
        self.horizontalLayout_6.addWidget(self.button_signal)
        self.button_math = QtWidgets.QToolButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_math.setIcon(icon3)
        self.button_math.setObjectName("button_math")
        self.horizontalLayout_6.addWidget(self.button_math)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.list_pre = QtWidgets.QListWidget(self.centralwidget)
        self.list_pre.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_pre.setStyleSheet("background:rgb(255, 255, 215)")
        self.list_pre.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.list_pre.setObjectName("list_pre")
        self.verticalLayout_6.addWidget(self.list_pre)
        self.verticalLayout_6.setStretch(1, 6)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("border:none;\n"
"background-color:rgb(222, 222, 222);\n"
"max-height : 3px;\n"
"")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 255))")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_loadpost = QtWidgets.QToolButton(self.frame_2)
        self.button_loadpost.setIcon(icon)
        self.button_loadpost.setObjectName("button_loadpost")
        self.horizontalLayout_7.addWidget(self.button_loadpost)
        self.button_clearpost = QtWidgets.QToolButton(self.frame_2)
        self.button_clearpost.setIcon(icon1)
        self.button_clearpost.setObjectName("button_clearpost")
        self.horizontalLayout_7.addWidget(self.button_clearpost)
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.button_signalpost = QtWidgets.QToolButton(self.frame_2)
        self.button_signalpost.setIcon(icon2)
        self.button_signalpost.setObjectName("button_signalpost")
        self.horizontalLayout_7.addWidget(self.button_signalpost)
        self.b = QtWidgets.QToolButton(self.frame_2)
        self.b.setIcon(icon3)
        self.b.setObjectName("b")
        self.horizontalLayout_7.addWidget(self.b)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.list_post = QtWidgets.QListWidget(self.centralwidget)
        self.list_post.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_post.setStyleSheet("background:rgb(255, 255, 215)")
        self.list_post.setObjectName("list_post")
        self.verticalLayout_5.addWidget(self.list_post)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("border:none;\n"
"background-color:rgb(222, 222, 222);\n"
"max-height : 10px;\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_onepage = QtWidgets.QToolButton(self.frame_3)
        self.button_onepage.setStyleSheet("border:2px solid rgb(170, 170, 170);\n"
"border-radius:15px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/one_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_onepage.setIcon(icon4)
        self.button_onepage.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_onepage.setObjectName("button_onepage")
        self.horizontalLayout_8.addWidget(self.button_onepage)
        self.button_twopage = QtWidgets.QToolButton(self.frame_3)
        self.button_twopage.setStyleSheet("border:2px solid rgb(170, 170, 170);\n"
"border-radius:15px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/two_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_twopage.setIcon(icon5)
        self.button_twopage.setIconSize(QtCore.QSize(16, 16))
        self.button_twopage.setObjectName("button_twopage")
        self.horizontalLayout_8.addWidget(self.button_twopage)
        self.button_compare = QtWidgets.QToolButton(self.frame_3)
        self.button_compare.setStyleSheet("border:2px solid rgb(170, 170, 170);\n"
"border-radius:15px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_compare.setIcon(icon6)
        self.button_compare.setObjectName("button_compare")
        self.horizontalLayout_8.addWidget(self.button_compare)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background:rgb(255, 255, 255)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page.setObjectName("page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 731, 693))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_12.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_10.addWidget(self.scrollArea_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 98, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_10.addWidget(self.scrollArea_3)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.setStretch(1, 6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(2, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menu_2)
        self.menu_4.setObjectName("menu_4")
        self.menu_6 = QtWidgets.QMenu(self.menu_2)
        self.menu_6.setObjectName("menu_6")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.load_prefile = QtWidgets.QAction(MainWindow)
        self.load_prefile.setObjectName("load_prefile")
        self.load_editfile = QtWidgets.QAction(MainWindow)
        self.load_editfile.setObjectName("load_editfile")
        self.signal_enhance = QtWidgets.QAction(MainWindow)
        self.signal_enhance.setObjectName("signal_enhance")
        self.zongxian_enhance = QtWidgets.QAction(MainWindow)
        self.zongxian_enhance.setObjectName("zongxian_enhance")
        self.arith_enhance = QtWidgets.QAction(MainWindow)
        self.arith_enhance.setObjectName("arith_enhance")
        self.analyzesignal_pre = QtWidgets.QAction(MainWindow)
        self.analyzesignal_pre.setObjectName("analyzesignal_pre")
        self.analyzesignal_post = QtWidgets.QAction(MainWindow)
        self.analyzesignal_post.setObjectName("analyzesignal_post")
        self.analyzearith_pre = QtWidgets.QAction(MainWindow)
        self.analyzearith_pre.setObjectName("analyzearith_pre")
        self.analyzearith_post = QtWidgets.QAction(MainWindow)
        self.analyzearith_post.setObjectName("analyzearith_post")
        self.menu.addAction(self.load_prefile)
        self.menu.addSeparator()
        self.menu.addAction(self.load_editfile)
        self.menu_4.addAction(self.analyzesignal_pre)
        self.menu_4.addAction(self.analyzesignal_post)
        self.menu_6.addAction(self.analyzearith_pre)
        self.menu_6.addAction(self.analyzearith_post)
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_6.menuAction())
        self.menu_3.addAction(self.signal_enhance)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.zongxian_enhance)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.arith_enhance)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_loadpre.setToolTip(_translate("MainWindow", "导入原始代码"))
        self.button_loadpre.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>导入原始代码</p></body></html>"))
        self.button_loadpre.setText(_translate("MainWindow", "..."))
        self.button_clearpre.setToolTip(_translate("MainWindow", "清空所加载代码"))
        self.button_clearpre.setText(_translate("MainWindow", "..."))
        self.button_signal.setToolTip(_translate("MainWindow", "关键信号分析"))
        self.button_signal.setText(_translate("MainWindow", "..."))
        self.button_math.setToolTip(_translate("MainWindow", "核心算法分析"))
        self.button_math.setText(_translate("MainWindow", "..."))
        self.button_loadpost.setToolTip(_translate("MainWindow", "导入增强后代码"))
        self.button_loadpost.setText(_translate("MainWindow", "..."))
        self.button_clearpost.setToolTip(_translate("MainWindow", "清空所加载代码"))
        self.button_clearpost.setText(_translate("MainWindow", "..."))
        self.button_signalpost.setToolTip(_translate("MainWindow", "安全性分析"))
        self.button_signalpost.setText(_translate("MainWindow", "..."))
        self.b.setText(_translate("MainWindow", "..."))
        self.button_onepage.setToolTip(_translate("MainWindow", "单页显示"))
        self.button_onepage.setText(_translate("MainWindow", "单页"))
        self.button_twopage.setToolTip(_translate("MainWindow", "双页显示"))
        self.button_twopage.setText(_translate("MainWindow", "双页"))
        self.button_compare.setToolTip(_translate("MainWindow", "代码对比"))
        self.button_compare.setText(_translate("MainWindow", "对比"))
        self.label.setText(_translate("MainWindow", "代码展示页"))
        self.label_2.setText(_translate("MainWindow", "双页"))
        self.label_3.setText(_translate("MainWindow", "双页"))
        self.menu.setTitle(_translate("MainWindow", "导入文件"))
        self.menu_2.setTitle(_translate("MainWindow", "代码安全性分析"))
        self.menu_4.setTitle(_translate("MainWindow", "关键信号分析"))
        self.menu_6.setTitle(_translate("MainWindow", "核心算法分析"))
        self.menu_3.setTitle(_translate("MainWindow", "代码安全增强"))
        self.load_prefile.setText(_translate("MainWindow", "原始代码"))
        self.load_prefile.setToolTip(_translate("MainWindow", "原始代码"))
        self.load_editfile.setText(_translate("MainWindow", "增强后代码"))
        self.load_editfile.setToolTip(_translate("MainWindow", "更新后代码"))
        self.signal_enhance.setText(_translate("MainWindow", "关键信号安全增强"))
        self.zongxian_enhance.setText(_translate("MainWindow", "总线传输安全增强"))
        self.arith_enhance.setText(_translate("MainWindow", "核心算法安全增强"))
        self.analyzesignal_pre.setText(_translate("MainWindow", "原始代码"))
        self.analyzesignal_post.setText(_translate("MainWindow", "增强后代码"))
        self.analyzearith_pre.setText(_translate("MainWindow", "原始代码"))
        self.analyzearith_post.setText(_translate("MainWindow", "增强后代码"))

